## Torch

In [18]:
import torch
import torch.nn as nn

In [19]:
model = nn.Sequential(nn.Linear(2,3),nn.ReLU(),nn.Linear(3,1))

In [34]:
rand_vec=(torch.tensor([0.4983, 0.4915]))

In [35]:
rand_vec

tensor([0.4983, 0.4915])

In [36]:
model(rand_vec)

tensor([0.4111], grad_fn=<AddBackward0>)

In [37]:
model

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
)

In [49]:
torch.onnx.export(model.to(torch.float32),               
                  rand_vec.to(torch.float32),                         
                  "torch.onnx",  
                  input_names = ['input_1'],)


## Sklearn

In [75]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType
iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y)
clr = LogisticRegression()
clr.fit(X_train, y_train)


LogisticRegression()

In [76]:
initial_type = [('input_1', FloatTensorType([]))]
onx = convert_sklearn(clr, initial_types=initial_type,
                      options = {id(clr): {'zipmap': False, 'output_class_labels': False}}
)
with open("rf.onnx", "wb") as f:
    f.write(onx.SerializeToString())


In [79]:
import numpy as np
tst=np.array([5.1, 3.4, 1.5, 0.2])

In [86]:
clr.predict_proba(tst.reshape(1, -1))

array([[9.70724332e-01, 2.92755070e-02, 1.61450810e-07]])

In [95]:
from catboost import CatBoostClassifier 
cb=CatBoostClassifier()
cb.fit(X_train, y_train)

Learning rate set to 0.070767
0:	learn: 1.0191421	total: 3.43ms	remaining: 3.43s
1:	learn: 0.9458538	total: 6.25ms	remaining: 3.12s
2:	learn: 0.8823557	total: 9.46ms	remaining: 3.14s
3:	learn: 0.8249462	total: 12.6ms	remaining: 3.14s
4:	learn: 0.7691594	total: 14.5ms	remaining: 2.88s
5:	learn: 0.7218937	total: 18.4ms	remaining: 3.05s
6:	learn: 0.6802684	total: 22.8ms	remaining: 3.23s
7:	learn: 0.6395819	total: 26.2ms	remaining: 3.24s
8:	learn: 0.6047886	total: 29.7ms	remaining: 3.27s
9:	learn: 0.5681539	total: 32.9ms	remaining: 3.26s
10:	learn: 0.5329595	total: 35ms	remaining: 3.15s
11:	learn: 0.5054147	total: 36.9ms	remaining: 3.04s
12:	learn: 0.4805397	total: 38.9ms	remaining: 2.95s
13:	learn: 0.4518530	total: 40.1ms	remaining: 2.82s
14:	learn: 0.4306889	total: 41.4ms	remaining: 2.72s
15:	learn: 0.4098161	total: 42.6ms	remaining: 2.62s
16:	learn: 0.3908078	total: 44.3ms	remaining: 2.56s
17:	learn: 0.3728134	total: 46ms	remaining: 2.51s
18:	learn: 0.3575950	total: 47.2ms	remaining: 2.

252:	learn: 0.0143675	total: 169ms	remaining: 499ms
253:	learn: 0.0143127	total: 171ms	remaining: 502ms
254:	learn: 0.0142450	total: 172ms	remaining: 502ms
255:	learn: 0.0142034	total: 173ms	remaining: 502ms
256:	learn: 0.0141448	total: 173ms	remaining: 501ms
257:	learn: 0.0140618	total: 174ms	remaining: 500ms
258:	learn: 0.0139887	total: 174ms	remaining: 499ms
259:	learn: 0.0139178	total: 175ms	remaining: 498ms
260:	learn: 0.0138764	total: 176ms	remaining: 497ms
261:	learn: 0.0138229	total: 176ms	remaining: 496ms
262:	learn: 0.0137687	total: 177ms	remaining: 496ms
263:	learn: 0.0137182	total: 177ms	remaining: 495ms
264:	learn: 0.0136762	total: 178ms	remaining: 494ms
265:	learn: 0.0136247	total: 179ms	remaining: 493ms
266:	learn: 0.0135463	total: 179ms	remaining: 493ms
267:	learn: 0.0134822	total: 180ms	remaining: 492ms
268:	learn: 0.0134126	total: 181ms	remaining: 491ms
269:	learn: 0.0133460	total: 181ms	remaining: 491ms
270:	learn: 0.0133033	total: 182ms	remaining: 490ms
271:	learn: 

550:	learn: 0.0060629	total: 346ms	remaining: 282ms
551:	learn: 0.0060487	total: 347ms	remaining: 281ms
552:	learn: 0.0060358	total: 347ms	remaining: 281ms
553:	learn: 0.0060233	total: 348ms	remaining: 280ms
554:	learn: 0.0060099	total: 348ms	remaining: 279ms
555:	learn: 0.0060011	total: 349ms	remaining: 278ms
556:	learn: 0.0059876	total: 349ms	remaining: 278ms
557:	learn: 0.0059747	total: 349ms	remaining: 277ms
558:	learn: 0.0059641	total: 350ms	remaining: 276ms
559:	learn: 0.0059513	total: 350ms	remaining: 275ms
560:	learn: 0.0059395	total: 351ms	remaining: 274ms
561:	learn: 0.0059259	total: 351ms	remaining: 274ms
562:	learn: 0.0059162	total: 352ms	remaining: 273ms
563:	learn: 0.0059028	total: 353ms	remaining: 273ms
564:	learn: 0.0058936	total: 353ms	remaining: 272ms
565:	learn: 0.0058768	total: 354ms	remaining: 271ms
566:	learn: 0.0058651	total: 354ms	remaining: 271ms
567:	learn: 0.0058558	total: 355ms	remaining: 270ms
568:	learn: 0.0058467	total: 355ms	remaining: 269ms
569:	learn: 

928:	learn: 0.0035149	total: 527ms	remaining: 40.3ms
929:	learn: 0.0035100	total: 528ms	remaining: 39.7ms
930:	learn: 0.0035060	total: 528ms	remaining: 39.2ms
931:	learn: 0.0035024	total: 529ms	remaining: 38.6ms
932:	learn: 0.0034979	total: 530ms	remaining: 38ms
933:	learn: 0.0034947	total: 530ms	remaining: 37.5ms
934:	learn: 0.0034906	total: 531ms	remaining: 36.9ms
935:	learn: 0.0034860	total: 531ms	remaining: 36.3ms
936:	learn: 0.0034833	total: 532ms	remaining: 35.8ms
937:	learn: 0.0034799	total: 533ms	remaining: 35.2ms
938:	learn: 0.0034760	total: 534ms	remaining: 34.7ms
939:	learn: 0.0034724	total: 534ms	remaining: 34.1ms
940:	learn: 0.0034693	total: 535ms	remaining: 33.5ms
941:	learn: 0.0034659	total: 535ms	remaining: 32.9ms
942:	learn: 0.0034633	total: 536ms	remaining: 32.4ms
943:	learn: 0.0034595	total: 536ms	remaining: 31.8ms
944:	learn: 0.0034566	total: 537ms	remaining: 31.2ms
945:	learn: 0.0034530	total: 538ms	remaining: 30.7ms
946:	learn: 0.0034495	total: 538ms	remaining: 30

In [96]:
tst=np.array([5.1, 3.4, 1.5, 0.2])

In [97]:
cb.predict_proba(X_train[0].reshape(1, -1))

array([[9.99380657e-01, 3.43438605e-04, 2.75903968e-04]])

In [98]:
cb.save_model("cb.cbm",
           format="cbm",
)